### ISSUE TITLE
Reporter should show "dots" while executing tests

### ISSUE THREAD

**Issue by psbanka** [ciena-blueplanet/ember-test-utils#25]
The mocha `dots` reporter does this well: https://github.com/gurdiga/mocha-html-dot-reporter ... can we get dots going when tests are running so that a dev is not left scratching her head wondering if tests are running or not?

**Comment by job13er** [comment]
Are you referring to the custom reporter provided by this addon? B/c I haven't seen a reporter that doesn't show tests as they're executing yet, but I haven't used the reporter provided by this addon yet either.

**Comment by sandersky** [comment]
@job13er the issue with this reporter is it only reports failures as it executes. In the even all of your tests pass it dumps the results out at the end because it sorts them by execution time. So I think the solution may be to print a dot on each success as the tests run so you know things are happening. In the even of a successful test run you'd end up see dots for every test as they execute followed by a dump of the sorted results at the end.
